name: CI/CD - Deploy to GitHub Pages

on:
  push:
    branches:
      - 'main'
    paths:
      - 'apps/angular-client/**'
  pull_request:
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # Lint affected projects (optional, uncomment if needed)
      # - name: Lint affected projects
      #   run: npx nx affected -t lint

      - name: Build angular-client app
        run: npx nx build angular-client --configuration=production --base-href /${{ github.event.repository.name }}/

      - name: Create 404.html
        run: cp build/apps/angular-client/index.html build/apps/angular-client/404.html

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build/apps/angular-client'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
