name: CI/CD - Automate Git Tag Versioning

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  tag-version:
    name: Automate Git Tag Versioning
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (if using package.json for versioning)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Step 3: Extract version from package.json
      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version: $VERSION"

      # Step 4: Create a new Git tag
      - name: Create Git tag
        id: create_tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a "v${VERSION}" -m "Release version ${VERSION}"
          echo "Created tag v${VERSION}"

      # Step 5: Push the tag to the remote repository
      - name: Push Git tag
        run: |
          git push origin "v${VERSION}"
